PACKAGE_NAME="t2bce_core"
PACKAGE_VERSION="0.06"

MAKE[0]="make KVERSION=${kernelver} T2BCE_DMA_SRC=t2bce_dma"

BUILT_MODULE_NAME[0]="t2bce_core"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
