site_name: KAIT2EN Fedora
site_url: https://kait2en.github.io/
repo_url: https://github.com/kaiT2en/KaiT2en-Fedora
repo_name: kaiT2en/KAIT2EN-Fedora
docs_dir: docs
site_dir: site
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list

theme:
  name: material
  logo: assets/kaiT2en-logo-tr.png
  favicon: assets/kaiT2en-logo-tr.png
  palette:
    scheme: slate
    primary: black
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Post-install:
      - Audio DSP: post-install/audio-dsp.md
      - Configure GPUs: post-install/configuring-gpus.md
      - Hardware video decoding: post-install/hardware-video-decoding.md
      - Updating: post-install/updating.md
  - Reference:
      - Installed files: reference/installed-files.md
