PACKAGE_NAME="t2thunderbolt"
PACKAGE_VERSION="0.2"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build KVER=${kernelver}"

BUILT_MODULE_NAME[0]="t2thunderbolt"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
