SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Internal Speakers"

	Value {
		PlaybackPriority 100
		PlaybackChannels "${var:SpeakerChannels}"
		PlaybackPCM "hw:${CardId},0"
	}
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	Value {
		CapturePriority 300
		CaptureChannels 3
		CaptureRate 48000
		CapturePCM "hw:${CardId},1"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones"

	Value {
		PlaybackPriority 300
		PlaybackChannels 2
		PlaybackPCM "hw:${CardId},2"
		JackControl "Codec Output Jack"
		JackHWMute "Speaker"
	}
}

SectionDevice."Headset" {
	Comment "Headset Microphone"

	Value {
		CapturePriority 200
		CaptureChannels 1
		CapturePCM "hw:${CardId},3"
	}
}
