PACKAGE_NAME="t2touchbar"
PACKAGE_VERSION="0.1"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build KVER=${kernelver}"

BUILT_MODULE_NAME[0]="t2hid"
BUILT_MODULE_NAME[1]="t2touchbar_bl"
BUILT_MODULE_NAME[2]="t2touchbar_kbd"

DEST_MODULE_LOCATION[0]="/updates/dkms"
DEST_MODULE_LOCATION[1]="/updates/dkms"
DEST_MODULE_LOCATION[2]="/updates/dkms"

AUTOINSTALL="yes"
