PACKAGE_NAME="t2bce_stack"
PACKAGE_VERSION="0.01"

MAKE[0]="make KVERSION=${kernelver}"

BUILT_MODULE_NAME[0]="t2bce_dma"
BUILT_MODULE_LOCATION[0]="t2bce_dma"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILT_MODULE_NAME[1]="t2bce_core"
BUILT_MODULE_LOCATION[1]="t2bce_core"
DEST_MODULE_LOCATION[1]="/updates/dkms"

BUILT_MODULE_NAME[2]="t2bce_vhci"
BUILT_MODULE_LOCATION[2]="t2bce_vhci"
DEST_MODULE_LOCATION[2]="/updates/dkms"

BUILT_MODULE_NAME[3]="t2bce_audio"
BUILT_MODULE_LOCATION[3]="t2bce_audio"
DEST_MODULE_LOCATION[3]="/updates/dkms"

BUILT_MODULE_NAME[4]="t2bce_ave"
BUILT_MODULE_LOCATION[4]="t2bce_ave"
DEST_MODULE_LOCATION[4]="/updates/dkms"

AUTOINSTALL="yes"
