#!/usr/bin/env bash

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)/lib.sh"

require_root
require_repo_root
require_fedora
require_command basename cp dnf find id install ln mktemp rm runuser sed systemctl

DSP_SRC="$REPO_ROOT/modules/t2bce_audio-dsp/firs"
DSP_DST_BASE="/usr/share/kait2en/audio-dsp"
WP_CONF_DIR="/etc/wireplumber/wireplumber.conf.d"
WP_CONF="$WP_CONF_DIR/51-kait2en-t2-dsp.conf"
WP_SCRIPT_DIR="/usr/share/wireplumber/scripts/device"

DSP_PACKAGES=(
	pipewire
	pipewire-pulseaudio
	wireplumber
	pipewire-module-filter-chain-lv2
	lv2-bankstown
	lv2-triforce
	lsp-plugins-lv2
	lv2-swh-plugins
)

model_dir_for_product() {
	case "$1" in
		MacBookPro15,1) printf '%s\n' "15_1" ;;
		MacBookPro16,1) printf '%s\n' "16_1" ;;
		MacBookPro16,4) printf '%s\n' "16_4" ;;
		MacBookAir9,1) printf '%s\n' "9_1" ;;
		*) return 1 ;;
	esac
}

apple_t2_audio_pci_tag() {
	local dev vendor device pci_id

	for dev in /sys/bus/pci/devices/*; do
		[[ -r "$dev/vendor" && -r "$dev/device" ]] || continue
		vendor="$(<"$dev/vendor")"
		device="$(<"$dev/device")"
		if [[ "$vendor" == "0x106b" && "$device" == "0x1803" ]]; then
			pci_id="$(basename "$dev")"
			printf '%s\n' "${pci_id//:/_}"
			return 0
		fi
	done

	return 1
}

target_user() {
	local user=${SUDO_USER:-}

	if [[ -n "$user" && "$user" != root ]]; then
		printf '%s\n' "$user"
	else
		return 1
	fi
}

restart_user_audio() {
	local user uid runtime

	if ! user="$(target_user)"; then
		warn "cannot determine non-root user; restart WirePlumber and PipeWire manually"
		return 0
	fi

	uid="$(id -u "$user")"
	runtime="/run/user/$uid"
	if [[ ! -d "$runtime" ]]; then
		warn "user runtime $runtime is not active; restart WirePlumber and PipeWire after login"
		return 0
	fi

	info "restarting WirePlumber and PipeWire for $user"
	if ! runuser -u "$user" -- env XDG_RUNTIME_DIR="$runtime" \
		systemctl --user restart wireplumber pipewire pipewire-pulse; then
		warn "could not restart user audio services; reboot or restart them manually"
	fi
}

install_graph() {
	local src=$1 dst=$2 old_audio_root=$3 new_audio_root=$4 new_target=$5 tmp

	tmp="$(mktemp)"
	sed \
		-e "s|$old_audio_root|$new_audio_root|g" \
		-e "s|\"target.object\": \"alsa_output.pci-[^\"]*\\.Speakers\"|\"target.object\": \"$new_target\"|g" \
		-e "s|\"target.object\": \"alsa_input.pci-[^\"]*\\.BuiltinMic\"|\"target.object\": \"$new_target\"|g" \
		"$src" >"$tmp"
	install -o root -g root -m 0644 "$tmp" "$dst"
	rm -f "$tmp"
}

product_name=
if [[ -r /sys/class/dmi/id/product_name ]]; then
	product_name="$(< /sys/class/dmi/id/product_name)"
fi
if [[ -z "$product_name" ]]; then
	info "skipping audio DSP: cannot detect product name"
	exit 0
fi

if ! model_dir="$(model_dir_for_product "$product_name")"; then
	info "skipping audio DSP: no DSP profile for $product_name"
	exit 0
fi

src_dir="$DSP_SRC/$model_dir"
if [[ ! -d "$src_dir" || ! -f "$src_dir/graph.json" ]]; then
	info "skipping audio DSP: missing DSP files for $product_name ($model_dir)"
	exit 0
fi

if ! pci_tag="$(apple_t2_audio_pci_tag)"; then
	fail "could not find Apple T2 audio PCI device 106b:1803"
fi

speaker_sink="alsa_output.pci-${pci_tag}.HiFi__Speaker__sink"
mic_source="alsa_input.pci-${pci_tag}.HiFi__Mic__source"
dst_dir="$DSP_DST_BASE/$model_dir"
old_audio_root="/usr/share/t2-linux-audio/$model_dir"

info "installing audio DSP for $product_name ($model_dir)"
dnf install -y "${DSP_PACKAGES[@]}"

install -d -o root -g root -m 0755 "$dst_dir"
find "$src_dir" -maxdepth 1 -type f \( -name '*.wav' -o -name '*.lua' \) \
	-exec install -o root -g root -m 0644 {} "$dst_dir/" \;

install_graph "$src_dir/graph.json" "$dst_dir/graph.json" \
	"$old_audio_root" "$dst_dir" \
	"$speaker_sink"

has_mic=0
if [[ -f "$src_dir/mic.json" ]]; then
	install_graph "$src_dir/mic.json" "$dst_dir/mic.json" \
		"$old_audio_root" "$dst_dir" \
		"$mic_source"
	has_mic=1
fi

if [[ -f "$dst_dir/t2-force-unmute.lua" ]]; then
	install -d -o root -g root -m 0755 "$WP_SCRIPT_DIR"
	ln -sf "$dst_dir/t2-force-unmute.lua" "$WP_SCRIPT_DIR/t2-force-unmute.lua"
fi

install -d -o root -g root -m 0755 "$WP_CONF_DIR"
rm -f /etc/pipewire/pipewire.conf.d/t2_*_speakers.conf
rm -f /etc/pipewire/pipewire.conf.d/t2_*_mic.conf
rm -f "$WP_CONF_DIR/51-t2-dsp.conf"

tmp_conf="$(mktemp)"
{
	printf '# WirePlumber configuration for KaiT2en Apple T2 audio DSP\n'
	printf '# Generated by scripts/fedora/install-dsp.sh for %s\n\n' "$product_name"
	printf 'node.software-dsp.rules = [\n'
	printf '    {\n'
	printf '        matches = [\n'
	printf '            { node.name = "%s" }\n' "$speaker_sink"
	printf '        ]\n'
	printf '        actions = { create-filter = { filter-path = "%s/graph.json" hide-parent = false } }\n' "$dst_dir"
	printf '    }\n'
	if (( has_mic )); then
		printf '    {\n'
		printf '        matches = [\n'
		printf '            { node.name = "%s" }\n' "$mic_source"
		printf '        ]\n'
		printf '        actions = { create-filter = { filter-path = "%s/mic.json" hide-parent = false } }\n' "$dst_dir"
		printf '    }\n'
	fi
	printf ']\n\n'
	if [[ -f "$dst_dir/t2-force-unmute.lua" ]]; then
		printf 'wireplumber.components = [\n'
		printf '    { name = %s/t2-force-unmute.lua, type = script/lua, provides = custom.kait2en-t2-audio }\n' "$dst_dir"
		printf ']\n\n'
		printf 'wireplumber.profiles = { main = { node.software-dsp = required custom.kait2en-t2-audio = required } }\n'
	else
		printf 'wireplumber.profiles = { main = { node.software-dsp = required } }\n'
	fi
} >"$tmp_conf"
install -o root -g root -m 0644 "$tmp_conf" "$WP_CONF"
rm -f "$tmp_conf"

restart_user_audio

info "audio DSP installed; raw speaker sink remains available next to the DSP sink"
