PACKAGE_NAME="t2gmux"
PACKAGE_VERSION="0.8"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build KVER=${kernelver}"

BUILT_MODULE_NAME[0]="t2gmux"
DEST_MODULE_LOCATION[0]="/updates/dkms"

AUTOINSTALL="yes"
